markw: Remove unsupported video decoder
11-24 15:35:03.278   628   865 E OMXNodeInstance: 
getExtensionIndex(0xf4f500c0:google.h263.decoder, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.279   628   865 E OMXNodeInstance: 
getExtensionIndex(0xf4f500c0:google.h263.decoder, 
OMX.google.android.index.enableAndroidNativeBuffers) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.299   628  2073 E OMXNodeInstance: 
getParameter(0xf4ba0284:qcom.decoder.hevc, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.299   628  2073 E OMXNodeInstance: 
getParameter(0xf4ba0284:qcom.decoder.hevc, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.300   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4ba0284:qcom.decoder.hevc, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
NotImplemented(0x80001006)
11-24 15:35:03.300   628  2073 E OMX-VDEC-1080P: set_parameter: Error: 
0x80001019, setting param 0x7f00005d
11-24 15:35:03.300   628  2073 E OMXNodeInstance: 
setParameter(0xf4ba0284:qcom.decoder.hevc, 
OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 
en=0) ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.301   522  2013 E LocSvc_APIClientBase: 
onCtrlCollectiveResponseCb:208] ERROR: 8 ID: 11
11-24 15:35:03.325   628   865 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.hevc.secure, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.325   628   865 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.hevc.secure, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.326   628   865 E OMXNodeInstance: 
getExtensionIndex(0xf4b67e04:qcom.decoder.hevc.secure, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
NotImplemented(0x80001006)
11-24 15:35:03.326   628   865 E OMX-VDEC-1080P: set_parameter: Error: 
0x80001019, setting param 0x7f00005d
11-24 15:35:03.326   628   865 E OMXNodeInstance: 
setParameter(0xf4b67e04:qcom.decoder.hevc.secure, 
OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 
en=0) ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.345   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f501e0:google.hevc.decoder, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.345   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f501e0:google.hevc.decoder, 
OMX.google.android.index.enableAndroidNativeBuffers) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.367   628  2073 E OMXNodeInstance: 
getParameter(0xf4ba0284:qcom.decoder.mpeg2, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.367   628  2073 E OMXNodeInstance: 
getParameter(0xf4ba0284:qcom.decoder.mpeg2, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.367   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4ba0284:qcom.decoder.mpeg2, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
NotImplemented(0x80001006)
11-24 15:35:03.367   628  2073 E OMX-VDEC-1080P: set_parameter: Error: 
0x80001019, setting param 0x7f00005d
11-24 15:35:03.367   628  2073 E OMXNodeInstance: 
setParameter(0xf4ba0284:qcom.decoder.mpeg2, 
OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 
en=0) ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.389   628  2073 E OMXNodeInstance: 
getParameter(0xf4ba0284:qcom.decoder.mpeg2.secure, ??(0x7f000044)) 
ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.390   628  2073 E OMXNodeInstance: 
getParameter(0xf4ba0284:qcom.decoder.mpeg2.secure, ??(0x7f000044)) 
ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.390   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4ba0284:qcom.decoder.mpeg2.secure, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
NotImplemented(0x80001006)
11-24 15:35:03.390   628  2073 E OMX-VDEC-1080P: set_parameter: Error: 
0x80001019, setting param 0x7f00005d
11-24 15:35:03.390   628  2073 E OMXNodeInstance: 
setParameter(0xf4ba0284:qcom.decoder.mpeg2.secure, 
OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 
en=0) ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.410   628  2073 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.mpeg4, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.410   628  2073 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.mpeg4, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.410   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4b67e04:qcom.decoder.mpeg4, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
NotImplemented(0x80001006)
11-24 15:35:03.410   628  2073 E OMX-VDEC-1080P: set_parameter: Error: 
0x80001019, setting param 0x7f00005d
11-24 15:35:03.410   628  2073 E OMXNodeInstance: 
setParameter(0xf4b67e04:qcom.decoder.mpeg4, 
OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 
en=0) ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.416   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f500c0:google.mpeg4.decoder, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.416   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f500c0:google.mpeg4.decoder, 
OMX.google.android.index.enableAndroidNativeBuffers) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.437   628  2073 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.vp8, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.437   628  2073 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.vp8, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.437   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4b67e04:qcom.decoder.vp8, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
NotImplemented(0x80001006)
11-24 15:35:03.437   628  2073 E OMX-VDEC-1080P: set_parameter: Error: 
0x80001019, setting param 0x7f00005d
11-24 15:35:03.437   628  2073 E OMXNodeInstance: 
setParameter(0xf4b67e04:qcom.decoder.vp8, 
OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 
en=0) ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.454  1861  1957 E         : 
[1124/153503.454689:ERROR:message_loop_thread.cc(69)] DoInThreadDelayed: 
message loop is null for thread bt_main_thread(-1), from pc:0x701a318478
11-24 15:35:03.454  1861  1957 E         : 
[1124/153503.454824:ERROR:btu_task.cc(89)] do_in_main_thread: failed 
from pc:0x701a318478
11-24 15:35:03.468   508   508 W DeviceHAL: Error from HAL Device in 
function set_mic_mute: Function not implemented
11-24 15:35:03.468   508   508 W DeviceHAL: Error from HAL Device in 
function set_mic_mute: Function not implemented
11-24 15:35:03.468   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f50180:google.vp8.decoder, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.468   508  1838 W DeviceHAL: Error from HAL Device in 
function set_mic_mute: Function not implemented
11-24 15:35:03.469   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f50180:google.vp8.decoder, 
OMX.google.android.index.enableAndroidNativeBuffers) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.490   628   865 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.vp9, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.491   628  2073 E OMXNodeInstance: 
getParameter(0xf4b67e04:qcom.decoder.vp9, ??(0x7f000044)) ERROR: 
UnsupportedSetting(0x80001019)
11-24 15:35:03.492   628   865 E OMXNodeInstance: 
getExtensionIndex(0xf4b67e04:qcom.decoder.vp9, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
NotImplemented(0x80001006)
11-24 15:35:03.492   628   865 E OMX-VDEC-1080P: set_parameter: Error: 
0x80001019, setting param 0x7f00005d
11-24 15:35:03.492   628   865 E OMXNodeInstance: 
setParameter(0xf4b67e04:qcom.decoder.vp9, 
OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 
en=0) ERROR: UnsupportedSetting(0x80001019)
11-24 15:35:03.502   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f501e0:google.vp9.decoder, 
OMX.google.android.index.configureVideoTunnelMode) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.502   628  2073 E OMXNodeInstance: 
getExtensionIndex(0xf4f501e0:google.vp9.decoder, 
OMX.google.android.index.enableAndroidNativeBuffers) ERROR: 
UnsupportedIndex(0x8000101a)
11-24 15:35:03.572   628   865 E OMXNodeInstance: 
getConfig(0xf4f500c0:google.h263.encoder, 
ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: Undefined(0x80001001)
11-24 15:35:03.572   628   865 E OMXNodeInstance: 
getParameter(0xf4f500c0:google.h263.encoder, 
ParamVideoIntraRefresh(0x6000006)) ERROR: UnsupportedIndex(0x8000101a)
11-24 15:35:03.603   640   640 I Atfwd_Daemon: 
qmi_client_register_error_cb status: 0
11-24 15:35:03.603   640   640 I Atfwd_Daemon: result : 0 	 ,Init step 
:1 	 ,qmiErrorCode: 0
11-24 15:35:03.610   628  2073 E OMXNodeInstance: 
getConfig(0xf4f50120:google.mpeg4.encoder, 
ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: Undefined(0x80001001)
11-24 15:35:03.610   628  2073 E OMXNodeInstance: 
getParameter(0xf4f50120:google.mpeg4.encoder, 
ParamVideoIntraRefresh(0x6000006)) ERROR: UnsupportedIndex(0x8000101a)
11-24 15:35:03.633   628  2073 E OMXNodeInstance: 
getConfig(0xf4f50000:google.vp8.encoder, 
ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: Undefined(0x80001001)
11-24 15:35:03.633   628  2073 E OMXNodeInstance: 
getParameter(0xf4f50000:google.vp8.encoder, 
ParamVideoIntraRefresh(0x6000006)) ERROR: UnsupportedIndex(0x8000101a)
11-24 15:35:03.637   628  2073 E OMXNodeInstance: 
getConfig(0xf4f50000:google.vp9.encoder, 
ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: Undefined(0x80001001)
11-24 15:35:03.637   628  2073 E OMXNodeInstance: 
getParameter(0xf4f50000:google.vp9.encoder, 
ParamVideoIntraRefresh(0x6000006)) ERROR: UnsupportedIndex(0x8000101a)